VENDOR_ART_START(Vulkan)
#include "Art/Vulkan.inc"
VENDOR_ART_END(Vulkan)

VENDOR_ART_START(AMD)
#include "Art/AMD.inc"
VENDOR_ART_END(AMD)

// VENDOR_ART_START(ImgTec)

VENDOR_ART_START(Apple)
#include "Art/Apple.inc"
VENDOR_ART_END(Apple)

VENDOR_ART_START(Nvidia)
#include "Art/Nvidia.inc"
VENDOR_ART_END(Nvidia)

// VENDOR_ART_START(ARM)

VENDOR_ART_START(Microsoft)
#include "Art/Microsoft.inc"
VENDOR_ART_END(Microsoft)

VENDOR_ART_START(Google)
#include "Art/Google.inc"
VENDOR_ART_END(Google)

VENDOR_ART_START(Qualcomm)
#include "Art/Qualcomm.inc"
VENDOR_ART_END(Qualcomm)

VENDOR_ART_START(Intel)
#include "Art/Intel.inc"
VENDOR_ART_END(Intel)

// VENDOR_ART_START(VIV)
// VENDOR_ART_START(VSI)
// VENDOR_ART_START(Kazan)
// VENDOR_ART_START(Codeplay)
// VENDOR_ART_START(Mesa)
// VENDOR_ART_START(Pocl)
// VENDOR_ART_START(MobileEye)