name: Build and Test

on: 
  push:
  pull_request:
  release:

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.0.2

    - name: Configure CMake
      env:
        CC: "gcc-10"
        CXX: "g++-10"
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: "linux"
        path: "build/vkfetch"

  create-release:
    needs: [linux-build]
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux Artifacts
      uses: actions/download-artifact@v1
      with:
        name: "linux"

    - name: Create release
      if: github.ref == 'refs/heads/main'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Build"
        files: |
          linux/vkfetch
